"""unic_token_ver_user_id

Revision ID: 31911458cd92
Revises: 52d00db3f5a6
Create Date: 2026-05-12 09:30:29.607850

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '31911458cd92'
down_revision: Union[str, Sequence[str], None] = '52d00db3f5a6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_token_versions_user_id'), table_name='token_versions')
    op.create_index(op.f('ix_token_versions_user_id'), 'token_versions', ['user_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_token_versions_user_id'), table_name='token_versions')
    op.create_index(op.f('ix_token_versions_user_id'), 'token_versions', ['user_id'], unique=False)
    # ### end Alembic commands ###
