# Generated by Django 6.0.2 on 2026-03-12 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_alter_personfilmwork_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='personfilmwork',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddIndex(
            model_name='filmwork',
            index=models.Index(fields=['updated_at'], name='film_work_updated_at_idx'),
        ),
        migrations.AddIndex(
            model_name='genre',
            index=models.Index(fields=['updated_at'], name='genre_updated_at_idx'),
        ),
        migrations.AddIndex(
            model_name='person',
            index=models.Index(fields=['updated_at'], name='person_updated_at_idx'),
        ),
        migrations.AddIndex(
            model_name='personfilmwork',
            index=models.Index(fields=['updated_at'], name='person_film_work_updated_idx'),
        ),
    ]
